# Generated by Django 5.0.4 on 2024-04-10 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Intitulé")),
                ("description", models.TextField(verbose_name="Description")),
                ("duration", models.CharField(max_length=100, verbose_name="Durée")),
                (
                    "salary",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Salaire"
                    ),
                ),
                (
                    "school_name",
                    models.CharField(max_length=255, verbose_name="Nom de l'école"),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="accounts.school",
                    ),
                ),
            ],
        ),
    ]
