# Generated by Django 5.0.4 on 2024-04-10 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="address",
            field=models.CharField(default="Address", max_length=255),
        ),
        migrations.AddField(
            model_name="school",
            name="school_name",
            field=models.CharField(default="School Name", max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="age",
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name="teacher",
            name="availability",
            field=models.CharField(default="Available", max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(default="First Name", max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(default="Last Name", max_length=100),
        ),
        migrations.AddField(
            model_name="teacher",
            name="years_of_experience",
            field=models.CharField(default="0-1 years", max_length=50),
        ),
        migrations.AlterField(
            model_name="school",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="school",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
