# Generated by Django 5.0.4 on 2024-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="desired_salary",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="diploma",
        ),
        migrations.RemoveField(
            model_name="professor",
            name="school_types",
        ),
        migrations.AddField(
            model_name="professor",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="phone_number",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="professor",
            name="years_of_experience",
            field=models.CharField(max_length=50),
        ),
    ]
